# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev6+g2cbea4f.d20230705'
__version_tuple__ = version_tuple = (0, 1, 'dev6', 'g2cbea4f.d20230705')
