FROM python:3.11-slim-bullseye

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y \
    dos2unix \
    gcc \
    git \
    libpq-dev \
    libsqlite3-dev  \
    procps \
    python3-dev \
    tmux \
    && rm -rf /var/lib/apt/lists/*

# Created by deploy script.
COPY requirements-jobs.txt requirements-jobs.txt

# Remove psycopg to install optimized local build later.
RUN awk '!/psycopg/' requirements-jobs.txt > tmpfile && mv tmpfile requirements-jobs.txt

RUN pip install --upgrade pip --no-cache-dir
RUN pip install -r requirements-jobs.txt --no-cache-dir

# Install psycopg3 optimized local build.
RUN pip install psycopg[c] --no-cache-dir

ARG OVERMIND_VERSION="v2.4.0"
ARG OVERMIND_URL="https://github.com/DarthSim/overmind/releases/download/${OVERMIND_VERSION}/overmind-${OVERMIND_VERSION}-linux-amd64.gz"
ARG OVERMIND_SHA256="1f7cac289b550a71bebf4a29139e58831b39003d9831be59eed3e39a9097311c"
# TODO: checksum not supported by fly.io. Running old version?
# --checksum=sha256:1f7cac289b550a71bebf4a29139e58831b39003d9831be59eed3e39a9097311c \
ADD ${OVERMIND_URL} ./
RUN echo "${OVERMIND_SHA256} ./overmind-${OVERMIND_VERSION}-linux-amd64.gz" \
    | sha256sum --check --status
RUN gzip -fd ./overmind-${OVERMIND_VERSION}-linux-amd64.gz
RUN mv ./overmind-${OVERMIND_VERSION}-linux-amd64 ./overmind
RUN chmod +x ./overmind
RUN mv ./overmind /usr/local/bin/

ARG USERNAME=overmind_user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN chown -R overmind_user /home/overmind_user/

USER overmind_user
WORKDIR /home/overmind_user/

COPY --chown=overmind_user:overmind_user ./ /home/overmind_user/

RUN dos2unix ./*

EXPOSE 8080

ENTRYPOINT ["bash", "run-jobs.sh"]
